name: Ruby CI

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo $RAILS_ENV
      # - name: Setup Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: 2.6.6
      # - name: Install
      #   run: bundle install --without production
      # - name: Run tests
      #   run: rails test
